Repository Mellanox/hw-mgmt, pull requests merged in 2022-08, with the labels that each got.

#547 hw-mgmt: scripts: add conversion of SMBIOS alternative BOM devtree file to csv format.
  usr/usr/bin/hw-management-devtree-check.sh
  usr/usr/bin/hw-management-devtree.sh
Labels: TAG

#549 hw-mgmt: scripts: fix removal of component in SMBIOS BOM string.
  usr/usr/bin/hw-management-devtree.sh
Labels: Add TAG

#554 hw-mgmt: rules: Rename line card interfaces
  usr/usr/bin/hw-management-if-rename.sh
Labels: Add TAG, Update changelog
